### ISSUE TITLE
sphinx_astrorefs is using deprecated API from sphinx

### ISSUE THREAD

**Issue by r-xue** [r-xue/pipeline#4]
```python
locale_dir /zfs/nvme/Workspace/nrao/tickets/PIPE-1669/paris/docs/source/locales/en/LC_MESSAGES does not exist
done
Original exception:
Traceback (most recent call last):
  File "/opt/miniforge3/envs/pipe1669/lib/python3.10/site-packages/sphinx/registry.py", line 453, in load_extension
    mod = import_module(extname)
  File "/opt/miniforge3/envs/pipe1669/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/miniforge3/envs/pipe1669/lib/python3.10/site-packages/sphinx_astrorefs/__init__.py", line 3, in <module>
    from . import reformat
  File "/opt/miniforge3/envs/pipe1669/lib/python3.10/site-packages/sphinx_astrorefs/reformat.py", line 7, in <module>
    from sphinx.util import logging, status_iterator
ImportError: cannot import name 'status_iterator' from 'sphinx.util' (/opt/miniforge3/envs/pipe1669/lib/python3.10/site-packages/sphinx/util/__init__.py)

```

see readthedocs/sphinx-autoapi/issues/391

**Comment by jobovy** [comment]
This is fixed in `sphinx-astrorefs`'s `main` branch in [2a8382fac94318376f77a8c842166b1f973f9dac](https://github.com/jobovy/sphinx-astrorefs/commit/2a8382fac94318376f77a8c842166b1f973f9dac)

**Comment by r-xue** [comment]
Thanks @jobovy for the fix!
